#!/usr/bin/env node
//项目启动
var debug = require('debug')('my-application');
var app = require('./app');

app.set('port', process.env.PORT || 80);

var server = app.listen(app.get('port'), function() {
  debug('微信服务器启动  端口:' + server.address().port);
  console.log('微信服务器启动 端口:' + server.address().port);
});
