SELECT 
    TP.PRONAME, TI . *
FROM
    T_INVENTORY TI
        LEFT JOIN
    T_PRODUCT TP ON TI.IPRODUCT = TP.ID
WHERE
    TI.DELFLAG = 0 AND TP.DELFLAG = 0
        AND TI.USERID = 1
		AND TI.ITYPE = 1
        AND TP.PRONAME = '管钳'
ORDER BY 
	TI.ID DESC 