-- 字母匹配查询单价
SELECT 
    TP.PRONAME,
    TP.PROLETTERS,
    TP.ID AS 'PID',
    TI.ITYPE,
    TI.ID AS 'ID',
    count(TP.PRONAME) AS 'NUM'
FROM
    T_INVENTORY TI
        LEFT JOIN
    T_PRODUCT TP ON TI.IPRODUCT = TP.ID
WHERE
    TI.DELFLAG = 0 AND TP.DELFLAG = 0
        AND TI.USERID = 1
        AND TI.ITYPE = '1'
        AND TP.PROLETTERS LIKE 'gj%'
GROUP BY 
	TP.PRONAME

ORDER BY 
		TP.HOT,TP.ID 

	
